version: '3.3'

services:
   db:
     image: mysql:5.7
     volumes:
       - ./.database:/var/lib/mysql
     environment:
       MYSQL_ROOT_PASSWORD: Disci9rootltn
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: endmay

   wordpress:
     depends_on:
       - db
     image: wordpress:latest
     ports:
       - "80:80"
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: endmay
     volumes:
       - ./src/wordpress:/var/www/html
       - ./src/php/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
     working_dir: /var/www/html

   phpmyadmin:
     image: phpmyadmin/phpmyadmin
     container_name: phpmyadmin
     environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
     ports:
      - 8080:80
